AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM Automation Lab - Creates IAM Users, Groups, and EventBridge Rule"
Parameters:
  S3UserName:
    Type: String
    Default: "s3-user"
    Description: "IAM username for S3 access"
  EC2UserName:
    Type: String
    Default: "ec2-user"
    Description: "IAM username for EC2 access"
  S3UserEmail:
    Type: String
    Default: "s3user@example.com"
    Description: "Email for the S3 user"
  EC2UserEmail:
    Type: String
    Default: "ec2user@example.com"
    Description: "Email for the EC2 user"
Resources:
  # 1. One-Time Password in Secrets Manager
  TempPasswordSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "OneTimePassword"
      Description: "Temporary password for IAM users"
      GenerateSecretString:
        SecretStringTemplate: '{"Password":"Default@123"}'
        GenerateStringKey: "Password"
        PasswordLength: 12
        ExcludeCharacters: '"@/\'
  # 2. IAM Groups
  S3UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "S3UserGroup"
      Policies:
        - PolicyName: "S3ReadAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "s3:ListBucket"
                Resource: "*"
  EC2UserGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: "EC2UserGroup"
      Policies:
        - PolicyName: "EC2ReadAccess"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "ec2:DescribeInstances"
                Resource: "*"
  # 3. IAM Users
  S3User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref S3UserName
      Groups:
        - !Ref S3UserGroup
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:OneTimePassword:SecretString:Password}}"
        PasswordResetRequired: true
  EC2User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref EC2UserName
      Groups:
        - !Ref EC2UserGroup
      LoginProfile:
        Password: !Sub "{{resolve:secretsmanager:OneTimePassword:SecretString:Password}}"
        PasswordResetRequired: true
  # 4. Store User Emails in Parameter Store
  S3UserEmailParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/IAM/${S3UserName}-email"
      Type: String
      Value: !Ref S3UserEmail
  EC2UserEmailParam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/IAM/${EC2UserName}-email"
      Type: String
      Value: !Ref EC2UserEmail
  # 5. EventBridge Rule
  IAMUserEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "IAMUserCreationRule"
      EventPattern:
        source:
          - "aws.iam"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "iam.amazonaws.com"
          eventName:
            - "CreateUser"
      Targets:
        - Arn: !GetAtt IAMUserLambda.Arn
          Id: "IAMUserLambdaTarget"
  # 6. Lambda Function
  IAMUserLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "LogNewIAMUsers"
      Runtime: python3.9
      Role: !GetAtt IAMUserLambdaRole.Arn
      Handler: "index.lambda_handler"
      Code:
        ZipFile: |
          import boto3
          import json
          import logging
          def lambda_handler(event, context):
              ssm = boto3.client('ssm')
              secretsmanager = boto3.client('secretsmanager')
              # Extract username from event
              user_name = event['detail']['requestParameters']['userName']
              try:
                  # Retrieve email and password
                  email_param_name = f"/IAM/{user_name}-email"
                  email = ssm.get_parameter(Name=email_param_name)['Parameter']['Value']
                  temp_password = secretsmanager.get_secret_value(SecretId="OneTimePassword")['SecretString']
                  # Log the email and password
                  logging.info(f"New User Created: {user_name}")
                  logging.info(f"Email: {email}")
                  logging.info(f"Temporary Password: {temp_password}")
              except Exception as e:
                  logging.error(f"Error retrieving details for {user_name}: {str(e)}")
      Timeout: 10
  # IAM Role for Lambda
  IAMUserLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "IAMUserLambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "LambdaIAMUserLogPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                  - "secretsmanager:GetSecretValue"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"






